export enum SCREENS_ENUM {
  //OnBoarding Stack Screens
  ONBOARDING_MAIN_SCREEN = 'ONBOARDING_MAIN_SCREEN',

  //Profile Stack Screens
  EDIT_PROFILE_SCREEN = 'EDIT_PROFILE_SCREEN',

  //Home Stack Screens
  STAISTICS_SCREEN = 'STAISTICS_SCREEN',

  //Auth Stack Screens
  SIGN_IN_SCREEN = 'SIGN_IN_SCREEN',
  SIGN_UP_SCREEN = 'SIGN_UP_SCREEN',
  FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN',
  OTP_SCREEN = 'OTP_SCREEN',
  RESET_PASSWORD_SCREEN = 'RESET_PASSWORD_SCREEN',
  RESET_PASSWORD_SUCCESS_SCREEN = 'RESET_PASSWORD_SUCCESS_SCREEN',

  //Bottom Tab Screens
  LEARNING_MAIN_SCREEN = 'LEARNING_MAIN_SCREEN',
  PROFILE_MAIN_SCREEN = 'PROFILE_MAIN_SCREEN',
  HOME_MAIN_SCREEN = 'HOME_MAIN_SCREEN',

}
