export enum SCREENS_ENUM {
  //OnBoarding Stack Screens
  ONBOARDING_MAIN_SCREEN = 'ONBOARDING_MAIN_SCREEN',

  //Auth Stack Screens
  SIGN_IN_SCREEN = 'SIGN_IN_SCREEN',
  SIGN_UP_SCREEN = 'SIGN_UP_SCREEN',
  FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN',
  OTP_SCREEN = 'OTP_SCREEN',
  RESET_PASSWORD_SCREEN = 'RESET_PASSWORD_SCREEN',
  RESET_PASSWORD_SUCCESS_SCREEN = 'RESET_PASSWORD_SUCCESS_SCREEN',

  //Bottom Tab Screens
  HISTORY_MAIN_SCREEN = 'HISTORY_MAIN_SCREEN',
  PROFILE_MAIN_SCREEN = 'PROFILE_MAIN_SCREEN',
  HOME_MAIN_SCREEN = 'HOME_MAIN_SCREEN',

}
