export enum STACKS_ENUM {
  ONBOARDING_STACK = 'ONBOARDING_STACK',
  AUTH_STACK = 'AUTH_STACK',
  MAIN_STACK = 'MAIN_STACK',
  BOTTOM_TABS_STACK = 'BOTTOM_TABS_STACK',
  PROFILE_STACK = 'PROFILE_STACK',
  HOME_STACK = 'HOME_STACK'
}
