export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-gray-100 p-6 flex items-center justify-center">
      <div className="max-w-7xl bg-white p-8 rounded-lg shadow-md">
        <h1 className="text-3xl font-bold text-gray-800 mb-4">Privacy Policy</h1>
        <p className="text-gray-600 mb-4">Last updated: February 24, 2025</p>
        <p className="text-gray-600 mb-4">
          This Privacy Policy describes Our policies and procedures on the
          collection, use, and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p className="text-gray-600 mb-4">
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>

        <h2 className="text-xl font-semibold text-gray-700 mt-6">
          Interpretation and Definitions
        </h2>
        <h3 className="text-lg font-semibold text-gray-700 mt-4">Interpretation</h3>
        <p className="text-gray-600 mb-4">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>

        <h3 className="text-lg font-semibold text-gray-700 mt-4">Definitions</h3>
        <p className="text-gray-600 mb-4">For the purposes of this Privacy Policy:</p>
        <ul className="list-disc pl-6 text-gray-600 mb-4">
          <li>
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </li>
          <li>
            <strong>Application</strong> refers to SolarIDX, the software program
            provided by the Company.
          </li>
          <li>
            <strong>Company</strong> (referred to as "We", "Us" or "Our") refers
            to Sagax.ai.
          </li>
          <li>
            <strong>Country</strong> refers to: United States.
          </li>
          <li>
            <strong>Device</strong> means any device that can access the Service,
            such as a computer, cellphone, or digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li>
            <strong>Service</strong> refers to the Application.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself.
          </li>
          <li>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company or other legal entity on behalf of which
            such individual is accessing or using the Service.
          </li>
        </ul>

        <h2 className="text-xl font-semibold text-gray-700 mt-6">
          Collecting and Using Your Personal Data
        </h2>
        <h3 className="text-lg font-semibold text-gray-700 mt-4">Types of Data Collected</h3>
        <h4 className="text-md font-semibold text-gray-700 mt-4">Personal Data</h4>
        <p className="text-gray-600 mb-4">
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You, including but not limited to:
        </p>
        <ul className="list-disc pl-6 text-gray-600 mb-4">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Usage Data</li>
        </ul>

        <h4 className="text-md font-semibold text-gray-700 mt-4">Usage Data</h4>
        <p className="text-gray-600 mb-4">
          Usage Data is collected automatically when using the Service. It may
          include information such as Your Device's IP address, browser type,
          browser version, the pages of our Service that You visit, the time and
          date of Your visit, and other diagnostic data.
        </p>

        <h3 className="text-lg font-semibold text-gray-700 mt-4">Use of Your Personal Data</h3>
        <p className="text-gray-600 mb-4">
          The Company may use Personal Data for the following purposes:
        </p>
        <ul className="list-disc pl-6 text-gray-600 mb-4">
          <li>To provide and maintain our Service</li>
          <li>To manage Your Account</li>
          <li>For business transfers</li>
          <li>To manage Your requests</li>
          <li>For other purposes like data analysis and improving our Service</li>
        </ul>

        <h3 className="text-lg font-semibold text-gray-700 mt-4">Children's Privacy</h3>
        <p className="text-gray-600 mb-4">
          Our Service does not address anyone under the age of 13. We do not knowingly collect personally
          identifiable information from anyone under 13. If You are a parent or guardian and You are aware
          that Your child has provided Us with Personal Data, please contact Us.
        </p>

        <h3 className="text-lg font-semibold text-gray-700 mt-4">Changes to This Privacy Policy</h3>
        <p className="text-gray-600 mb-4">
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the
          new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service,
          prior to the change becoming effective.
        </p>

        <h2 className="text-xl font-semibold text-gray-700 mt-6">Contact Us</h2>
        <p className="text-gray-600">
          If you have any questions about this Privacy Policy, You can contact
          us at <span className="font-medium">support@solaridx.com</span>.
        </p>
      </div>
    </div>
  );
}